# analysis_options.yaml
include: package:effective_dart/analysis_options_strong.yaml

analyzer:
  exclude:
    - build/**
    - ios/**
    - android/**

linter:
  rules:
    # — conventions de nommage —──────────────────────────────────────────
    always_specify_types: true           # déclarer explicitement List<int> et pas juste var
    camel_case_types: true               # classes / enums en PascalCase
    constant_identifier_names: true      # constantes en UPPER_SNAKE_CASE
    non_constant_identifier_names: true  # variables/fonctions en lowerCamelCase
    library_prefixes: true               # préfixes de package cohérents

    # — retours à la ligne & longueur de ligne —──────────────────────────
    prefer_single_quotes: true            # guillemets simples par défaut
    lines_longer_than_80_chars: false     # bloquer >80 caractères
    avoid_escaping_inner_quotes: true

    # — espacement —──────────────────────────────────────────────────────
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    space_before_function_parenthesis: false
    space_in_empty_set_or_map_literals: true

    # — documentation & commentaires —───────────────────────────────────
    require_trailing_commas: true         # dernière valeur d’une liste/map avec virgule
    sort_pub_dependencies: true           # tri alphabétique dans pubspec.yaml
    comment_references: true              # @see doit référencer un élément existant
    public_member_api_docs: true          # doc-comment pour toutes les méthodes publiques

    # — Flutter spécifiques —────────────────────────────────────────────
    avoid_print: true                     # interdire les prints > utiliser logger
    use_key_in_widget_constructors: true  # forcer la gestion des clés
    prefer_const_constructors: true       # encourager const partout

    # — autres bonnes pratiques —────────────────────────────────────────
    avoid_return_types_on_setters: true
    cancel_subscriptions: true
    depend_on_referenced_packages: true
    prefer_const_literals_to_create_immutables: true
    unused_import: true
    unnecessary_this: true
