name: Build and Release Flutter App

on:
  push:
    tags: ['*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: apk
            os: ubuntu-latest
            build_cmd: flutter build apk --release
            artifact: build/app/outputs/flutter-apk/app-release.apk
            asset: Epico-android.apk
          - platform: windows
            os: windows-latest
            build_cmd: flutter build windows --release
            artifact: build/windows/x64/runner/Release/Epico.exe
            asset: Epico_windows.exe
          - platform: macos
            os: macos-latest
            build_cmd: |
              flutter build macos --release
              ditto -c -k --sequesterRsrc --keepParent build/macos/Build/Products/Release/*.app app-macos.zip
            artifact: app-macos.zip
            asset: Epico-macos.zip
          - platform: linux
            os: ubuntu-latest
            setup: |
              sudo apt-get update
              sudo apt-get install -y libgtk-3-dev libunwind-dev pkg-config clang cmake ninja-build \
                libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
                gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
                libsecret-1-dev
            build_cmd: flutter build linux --release
            artifact: build/linux/x64/release/bundle/epico
            asset: Epico_linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install system deps
        if: matrix.setup != ''
        run: ${{ matrix.setup }}

      - name: Build
        run: ${{ matrix.build_cmd }}

      - name: Upload asset to the GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact }}
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
          overwrite: true
