name: Build and Release Flutter App

on:
  push:
    tags: ['*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- Android APK ---
          - platform: apk
            os: ubuntu-latest
            build_cmd: flutter build apk --release
            artifact: build/app/outputs/flutter-apk/app-release.apk
            asset: app-android.apk

          # --- Windows EXE ---
          - platform: windows
            os: windows-latest
            build_cmd: flutter build windows --release
            artifact: build/windows/runner/Release/app.exe
            asset: app-windows.exe

          # --- macOS .app (zippé) ---
          - platform: macos
            os: macos-latest
            build_cmd: |
              flutter build macos --release
              ditto -c -k --sequesterRsrc --keepParent \
                build/macos/Build/Products/Release/*.app app-macos.zip
            artifact: app-macos.zip
            asset: app-macos.zip

          # --- Linux ---
          - platform: linux
            os: ubuntu-latest
            setup: sudo apt-get update && sudo apt-get install -y libgtk-3-dev
            build_cmd: flutter build linux --release
            artifact: build/linux/runner/Release/app
            asset: app-linux

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'

      - name: Install Linux deps
        if: matrix.setup != ''
        run: ${{ matrix.setup }}

      - name: Build
        run: ${{ matrix.build_cmd }}

      - name: Upload asset to the GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact }}
          asset_name: ${{ matrix.asset }}
          tag: ${{ github.ref }}
          overwrite: true
